---
version: "3.8"

services:

  # nginx:
  #   container_name: nginx
  #   image: nginx:stable-alpine
  #   expose:
  #     - "80"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw

  frontend:
    container_name: web
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - "8080:4200"

  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./api
      dockerfile: Dockerfile
    # env_file:
    #   - server/settings.env
    environment:
      - ConnectionStrings__DefaultConnection=User ID=tokdok;Password=super_strong_password;Server=db;Port=5432;Database=tokdok;
      # - ASPNETCORE_URLS=http://+:80
    image: tokdok/api
    restart: always
    ports:
      - "8012:8080"
    volumes:
      - api:/etc/api
      - logs:/var/log/api

  db:
    environment:
      POSTGRES_USER: "tokdok"
      POSTGRES_PASSWORD: "super_strong_password"
      POSTGRES_DB: "tokdok"
      PGDATA: /var/lib/postgresql/data/tokdok
    ports:
      - "5433:5432"
    image: postgres:16
    restart: always
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  api:
  logs:
